import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import { Calculator, Zap, IndianRupee, BatteryCharging } from "lucide-react";

export function SolarCalculator({ triggerText = "Calculate Your Savings", className = "" }: { triggerText?: string, className?: string }) {
  const [monthlyBill, setMonthlyBill] = useState(3000);

  // Constants for calculation
  const UNIT_COST = 8; // Average cost per unit in INR
  const UNITS_PER_KW_PER_MONTH = 120; // Units generated by 1kW system in a month
  const COST_PER_KW = 60000; // Estimated cost per kW in INR

  // Calculations
  const monthlyUnits = monthlyBill / UNIT_COST;
  const recommendedKw = Math.max(1, Math.ceil((monthlyUnits / UNITS_PER_KW_PER_MONTH) * 10) / 10); // Round to 1 decimal place
  const totalCost = recommendedKw * COST_PER_KW;
  const zeroPercentEmi12Months = Math.round(totalCost / 12);
  const annualSavings = monthlyBill * 12;
  const lifetimeSavings = annualSavings * 25; // 25 years warranty

  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className={className}>
          <Calculator className="h-4 w-4" /> {triggerText}
        </button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px] rounded-3xl border-border bg-card p-6 shadow-soft">
        <DialogHeader>
          <DialogTitle className="font-display text-2xl font-bold text-foreground">
            Solar Savings Calculator
          </DialogTitle>
        </DialogHeader>

        <div className="mt-6 space-y-8">
          {/* Input Section */}
          <div>
            <div className="flex justify-between items-end mb-4">
              <label className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                Average Monthly Bill
              </label>
              <div className="font-display text-2xl font-bold text-primary">
                ₹{monthlyBill.toLocaleString('en-IN')}
              </div>
            </div>
            <Slider
              value={[monthlyBill]}
              onValueChange={(vals) => setMonthlyBill(vals[0])}
              min={500}
              max={20000}
              step={500}
              className="py-4"
            />
          </div>

          {/* Results Grid */}
          <div className="grid grid-cols-2 gap-4">
            <div className="rounded-2xl border border-border bg-background p-4">
              <div className="flex items-center gap-2 text-primary mb-2">
                <Zap className="h-4 w-4" />
                <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">System Size</span>
              </div>
              <div className="font-display text-xl font-bold text-foreground">{recommendedKw} kW</div>
              <p className="text-xs text-muted-foreground mt-1">Generates ~{Math.round(recommendedKw * UNITS_PER_KW_PER_MONTH)} units/mo</p>
            </div>

            <div className="rounded-2xl border border-border bg-background p-4">
              <div className="flex items-center gap-2 text-primary mb-2">
                <IndianRupee className="h-4 w-4" />
                <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Cost Estimate</span>
              </div>
              <div className="font-display text-xl font-bold text-foreground">₹{totalCost.toLocaleString('en-IN')}</div>
              <p className="text-xs text-muted-foreground mt-1">Before Gov. Subsidies</p>
            </div>

            <div className="col-span-2 rounded-2xl border border-primary/30 bg-primary/5 p-4 relative overflow-hidden">
              <div className="absolute -right-6 -top-6 h-24 w-24 rounded-full bg-primary/10 blur-xl"></div>
              <div className="flex items-center gap-2 text-primary mb-2 relative z-10">
                <BatteryCharging className="h-4 w-4" />
                <span className="text-xs font-semibold uppercase tracking-wider text-primary">0% EMI Option (12 Months)</span>
              </div>
              <div className="font-display text-2xl font-bold text-foreground relative z-10">
                ₹{zeroPercentEmi12Months.toLocaleString('en-IN')} <span className="text-sm font-normal text-muted-foreground">/ month</span>
              </div>
            </div>
            
            <div className="col-span-2 rounded-2xl bg-gradient-hero p-5 text-primary-foreground text-center">
              <div className="text-sm font-medium opacity-90 mb-1">Estimated 25-Year Savings</div>
              <div className="font-display text-3xl font-bold">₹{lifetimeSavings.toLocaleString('en-IN')}</div>
            </div>
          </div>
          
          <p className="text-center text-xs text-muted-foreground">
            *This is a preliminary estimate. Subsidies can reduce costs by up to 40%.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
